import { getDb } from "../db/database";
import { resolveAddressIdentities } from "./identity";
import { getAddress, id as hashText, isAddress, ZeroAddress } from "ethers";
import { createBackendPublicClient } from "./rpcClient";

export type DefiStrategyControl = "add" | "withdraw_partial" | "withdraw_all";
export type DefiStrategyAvailability = "live" | "preview" | "paused";
export type DefiStrategyAccess = "fast" | "moderate" | "longer";

export type DefiStrategy = {
  id: string;
  name: string;
  plainName?: string;
  description: string;
  provider: string;
  providerType: "morpho" | "aave" | "circle" | "mock" | "custom" | "souless";
  strategyType: "single-chain-vault" | "cross-chain-vault" | "mock-vault";
  status: "preview" | "pending_provider" | "ready" | "disabled";
  availability?: DefiStrategyAvailability;
  accessCategory?: DefiStrategyAccess;
  sourceChainId: number;
  sourceChainName: string;
  destinationChainId?: number;
  destinationChainName?: string;
  assetSymbol: string;
  assetAddress: string;
  assetDecimals: number;
  estimatedApy: number | null;
  riskLevel: "low" | "medium" | "high";
  minDepositRaw: string;
  targetAddress?: string;
  bridgeProvider?: string;
  exitTimeEstimate: string;
  userOwnsPosition: boolean;
  transactionEnabled: boolean;
  controls: DefiStrategyControl[];
  tags: string[];
  disclosures: string[];
  totalDepositedRaw?: string;
  participantCount?: number;
  icon?: string;
  bestFor?: string;
  balanceMovement?: string;
  details?: DefiStrategyDetails;
};

export type DefiPreviewPosition = {
  id: string;
  strategyId: string;
  status: "indexed";
  principalRaw: string;
  currentValueRaw: string;
  yieldEarnedRaw: string;
  chainState: string;
  updatedAt: number;
};

export type DefiStrategyDetails = {
  objective: string;
  asset: string;
  providerSummary: string;
  route: Array<{ label: string; value: string }>;
  risk: Array<{ label: string; value: string }>;
  addresses: Array<{ label: string; value: string }>;
  providerPayload: Record<string, string | number | boolean | null>;
};

export type DefiStrategyEvidence = {
  participantCount: number;
  yieldPaidRaw: string;
  updatedAt: number;
  participants: Array<{
    displayName: string;
    profileImageUrl: string | null;
  }>;
};

export type DefiActivityRecord = {
  id: string;
  timestamp: number;
  action: "grow" | "yield" | "withdraw" | "details" | "watch";
  strategyId: string;
  strategyName: string;
  amountRaw: string;
  direction: "in" | "out" | "neutral";
  status: "preview" | "pending" | "complete" | "failed";
  txHash?: string;
  detail?: string;
};

const ARC_TESTNET_CHAIN_ID = Number(process.env.CHAIN_ID || 5042002);
const ARC_USDC = process.env.USDC_ADDRESS || "0x3600000000000000000000000000000000000000";
const ENABLE_DEFI_TRANSACTIONS = process.env.ENABLE_DEFI_TRANSACTIONS === "true";
const DEFI_TRANSACTION_ROUTE_READY = process.env.DEFI_TRANSACTION_ROUTE_READY === "true";
const STRATEGY_PREVIEW_ABI = [{
  type: "function",
  name: "previewRedeem",
  stateMutability: "view",
  inputs: [{ name: "shares", type: "uint256" }],
  outputs: [{ name: "assets", type: "uint256" }],
}] as const;

function configuredAddress(name: string): string | undefined {
  const value = process.env[name]?.trim();
  return value && isAddress(value) && getAddress(value) !== ZeroAddress ? getAddress(value) : undefined;
}

function configuredSoulessStrategyId(): string {
  const value = process.env.DEFI_SOULESS_STRATEGY_ID?.trim() || "SOULESS_V3_GROWTH_73A95B_V1";
  return /^0x[0-9a-fA-F]{64}$/.test(value) ? value.toLowerCase() : hashText(value).toLowerCase();
}

function soulessStrategyStatus(): DefiStrategy["status"] {
  if (process.env.DEFI_SOULESS_STATUS === "disabled") return "disabled";
  const deploymentConfigured = Boolean(
    configuredAddress("DEFI_SOULESS_VAULT_ADDRESS") &&
    configuredAddress("DEFI_SOULESS_ADAPTER_ADDRESS") &&
    configuredAddress("DEFI_SOULESS_POOL_ADDRESS")
  );
  const verified = process.env.DEFI_SOULESS_DEPLOYMENT_VERIFIED === "true";
  const indexed = process.env.DEFI_SOULESS_INDEXED === "true";
  return process.env.DEFI_SOULESS_STATUS === "ready" && deploymentConfigured && verified && indexed
    ? "ready"
    : "pending_provider";
}

function soulessStrategies(): DefiStrategy[] {
  const vaultAddress = configuredAddress("DEFI_SOULESS_VAULT_ADDRESS");
  const adapterAddress = configuredAddress("DEFI_SOULESS_ADAPTER_ADDRESS");
  const poolAddress = configuredAddress("DEFI_SOULESS_POOL_ADDRESS");
  const status = soulessStrategyStatus();
  const estimatedApyRaw = process.env.DEFI_SOULESS_ESTIMATED_APY?.trim();
  const estimatedApy = estimatedApyRaw && Number.isFinite(Number(estimatedApyRaw))
    ? Number(estimatedApyRaw)
    : null;
  return [normalizeStrategy({
    id: configuredSoulessStrategyId(),
    name: "Growth",
    plainName: "Growth",
    description: "Put idle tips to work and receive a share of service fees generated by real network activity.",
    provider: "Souless",
    providerType: "souless",
    strategyType: "single-chain-vault",
    status,
    sourceChainId: ARC_TESTNET_CHAIN_ID,
    sourceChainName: "Arc Testnet",
    assetSymbol: "USDC",
    assetAddress: ARC_USDC,
    assetDecimals: 6,
    estimatedApy,
    riskLevel: "high",
    minDepositRaw: process.env.DEFI_MIN_DEPOSIT_RAW || "1000000",
    targetAddress: adapterAddress,
    exitTimeEstimate: "Usually within minutes, depending on network conditions",
    userOwnsPosition: true,
    transactionEnabled: false,
    controls: ["add", "withdraw_partial", "withdraw_all"],
    tags: ["Service fees", "Variable growth"],
    icon: "query_stats",
    bestFor: "Idle tips you are comfortable leaving to grow",
    balanceMovement: "Can move up or down",
    disclosures: [
      "Growth comes from service fees generated by real network activity, not from new participant deposits.",
      "Returns are variable and your current balance can be lower than the amount you added.",
      "You can request a withdrawal whenever you choose, but the returned amount and completion time depend on current network and market conditions.",
    ],
    details: {
      objective: "Help power digital-asset exchange activity and receive a proportional share of the service fees it generates.",
      asset: "USDC",
      providerSummary: "Souless provides the exchange infrastructure used by this static Growth strategy.",
      route: [
        { label: "You add", value: "Arc USDC from Tips Earned" },
        { label: "How growth happens", value: "A share of service fees from real network activity" },
        { label: "Access", value: "Withdraw to Tips Earned whenever you choose" },
      ],
      risk: [
        { label: "Balance", value: "Can rise or fall" },
        { label: "Growth", value: "Variable and not guaranteed" },
        { label: "Access", value: "May vary with network and market conditions" },
      ],
      addresses: [
        { label: "USDC", value: ARC_USDC },
        { label: "Strategy contract", value: vaultAddress || "Not deployed" },
        { label: "Teep connection", value: adapterAddress || "Not deployed" },
        { label: "Activity source", value: poolAddress || "Not deployed" },
      ],
      providerPayload: {
        provider: "Souless",
        rangeTemplate: "GROWTH",
        vaultAddress: vaultAddress || null,
        adapterAddress: adapterAddress || null,
        poolAddress: poolAddress || null,
        indexed: process.env.DEFI_SOULESS_INDEXED === "true",
        deploymentVerified: process.env.DEFI_SOULESS_DEPLOYMENT_VERIFIED === "true",
        automaticRefresh: false,
      },
    },
  })];
}

function parseStrategiesFromEnv(): DefiStrategy[] | null {
  const raw = process.env.DEFI_STRATEGIES_JSON;
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as DefiStrategy[];
    if (!Array.isArray(parsed)) return null;
    return parsed.map(normalizeStrategy);
  } catch (err) {
    console.warn("[DeFi] Ignoring invalid DEFI_STRATEGIES_JSON:", (err as Error).message);
    return null;
  }
}

function defaultStrategies(): DefiStrategy[] {
  const strategies: DefiStrategy[] = [
    {
      id: "teep-treasury-stable-preview",
      name: "Teep Treasury (Stable)",
      plainName: "Ready reserve",
      description: "Low risk capital preservation",
      provider: "Teep Treasury",
      providerType: "custom",
      strategyType: "mock-vault",
      status: "preview",
      sourceChainId: ARC_TESTNET_CHAIN_ID,
      sourceChainName: "Arc Testnet",
      assetSymbol: "USDC",
      assetAddress: ARC_USDC,
      assetDecimals: 6,
      estimatedApy: Number(process.env.DEFI_TEEP_TREASURY_PREVIEW_APY || 3.8),
      riskLevel: "low",
      minDepositRaw: process.env.DEFI_MIN_DEPOSIT_RAW || "1000000",
      exitTimeEstimate: "Usually minutes after exit",
      userOwnsPosition: true,
      transactionEnabled: false,
      controls: ["add", "withdraw_partial", "withdraw_all"],
      tags: ["Stable", "Low risk", "Preview"],
      icon: "security",
      bestFor: "Tips you may need again soon",
      balanceMovement: "Usually smaller",
      disclosures: [
        "Planning only: live growth actions are disabled for beta.",
        "This option is intended to model conservative stable-dollar growth.",
        "Provider and risk data must be refreshed before this can become a live strategy.",
      ],
      details: {
        objective: "Keep idle creator tips in a conservative stable-dollar growth option.",
        asset: "USDC",
        providerSummary: "Teep-managed preview strategy for conservative growth education.",
        route: [
          { label: "Starts on", value: "Arc Testnet" },
          { label: "Growth route", value: "Teep preview allocator" },
          { label: "Access back", value: "Usually minutes after exit" },
        ],
        risk: [
          { label: "Severity", value: "Low, not risk-free" },
          { label: "Return profile", value: "Gradual" },
          { label: "Transaction status", value: "Planning only" },
        ],
        addresses: [
          { label: "USDC", value: ARC_USDC },
          { label: "Strategy target", value: "Not deployed" },
        ],
        providerPayload: {
          provider: "Teep Treasury",
          apy: Number(process.env.DEFI_TEEP_TREASURY_PREVIEW_APY || 3.8),
          asset: "USDC",
          liveTransactions: false,
        },
      },
    },
    {
      id: "morpho-usdc-cross-chain-preview",
      name: "Morpho USDC Yield",
      plainName: "More growth potential",
      description: "Optimized lending on Base",
      provider: "Morpho",
      providerType: "morpho",
      strategyType: "cross-chain-vault",
      status: "pending_provider",
      sourceChainId: ARC_TESTNET_CHAIN_ID,
      sourceChainName: "Arc Testnet",
      destinationChainId: Number(process.env.DEFI_MORPHO_DESTINATION_CHAIN_ID || 84532),
      destinationChainName: process.env.DEFI_MORPHO_DESTINATION_CHAIN_NAME || "Base Sepolia",
      assetSymbol: "USDC",
      assetAddress: ARC_USDC,
      assetDecimals: 6,
      estimatedApy: Number(process.env.DEFI_MORPHO_PREVIEW_APY || 4.8),
      riskLevel: "low",
      minDepositRaw: process.env.DEFI_MIN_DEPOSIT_RAW || "1000000",
      targetAddress: process.env.MORPHO_VAULT_ADDRESS || "",
      bridgeProvider: "Circle CCTP / Arc App Kit",
      exitTimeEstimate: "Minutes after bridge finality",
      userOwnsPosition: true,
      transactionEnabled: false,
      controls: ["add", "withdraw_partial", "withdraw_all"],
      tags: ["Low risk", "Base Mainnet", "Preview"],
      icon: "account_balance",
      bestFor: "Tips you are unlikely to need soon",
      balanceMovement: "More noticeable",
      disclosures: [
        "Planning only: live deposits are disabled until Morpho and bridge addresses are verified.",
        "Funds should remain user-owned through the creator smart wallet when enabled.",
        "The strategy is provider-agnostic and can be replaced or joined by other approved providers.",
      ],
      details: {
        objective: "Route idle creator USDC into a Morpho-backed stable-dollar lending strategy.",
        asset: "USDC",
        providerSummary: "Morpho market metadata will be fetched from the provider before live rollout.",
        route: [
          { label: "Starts on", value: "Arc Testnet" },
          { label: "Bridge helper", value: "Circle CCTP / Arc App Kit" },
          { label: "Growth happens on", value: process.env.DEFI_MORPHO_DESTINATION_CHAIN_NAME || "Base Sepolia" },
          { label: "Access back", value: "Minutes after bridge finality" },
        ],
        risk: [
          { label: "Severity", value: "Low, not risk-free" },
          { label: "Return profile", value: "Variable" },
          { label: "Provider status", value: "Pending Arc listing verification" },
        ],
        addresses: [
          { label: "Arc USDC", value: ARC_USDC },
          { label: "Morpho vault", value: process.env.MORPHO_VAULT_ADDRESS || "Not listed yet" },
          { label: "Morpho bundler", value: process.env.MORPHO_BUNDLER_ADDRESS || "Not configured" },
          { label: "Destination USDC", value: process.env.CCTP_DESTINATION_USDC_ADDRESS || "Not configured" },
        ],
        providerPayload: {
          provider: "Morpho",
          apiUrl: process.env.MORPHO_API_URL || "https://api.morpho.org/graphql",
          vaultAddress: process.env.MORPHO_VAULT_ADDRESS || null,
          destinationChainId: Number(process.env.DEFI_MORPHO_DESTINATION_CHAIN_ID || 84532),
          bridgeProvider: "Circle CCTP / Arc App Kit",
          liveTransactions: false,
        },
      },
    },
  ];

  return strategies.map(normalizeStrategy);
}

function normalizeStrategy(strategy: DefiStrategy): DefiStrategy {
  const accessText = strategy.exitTimeEstimate.toLowerCase();
  const accessCategory: DefiStrategyAccess = strategy.accessCategory
    || (/longer|day|bridge|finality/.test(accessText)
      ? "longer"
      : /moderate|hour/.test(accessText)
        ? "moderate"
        : "fast");
  const availability: DefiStrategyAvailability = strategy.availability
    || (strategy.status === "ready" ? "live" : strategy.status === "disabled" ? "paused" : "preview");
  return {
    ...strategy,
    availability,
    accessCategory,
    description: strategy.description || `${strategy.provider} growth option`,
    tags: Array.isArray(strategy.tags) ? strategy.tags : [],
    disclosures: Array.isArray(strategy.disclosures) ? strategy.disclosures : [],
    controls: Array.isArray(strategy.controls) && strategy.controls.length
      ? strategy.controls
      : ["add", "withdraw_partial", "withdraw_all"],
    transactionEnabled: ENABLE_DEFI_TRANSACTIONS && DEFI_TRANSACTION_ROUTE_READY && strategy.status === "ready",
  };
}

export function listDefiStrategies(): DefiStrategy[] {
  return parseStrategiesFromEnv() || soulessStrategies();
}

export function getDefiStrategy(strategyId: string): DefiStrategy | null {
  return listDefiStrategies().find((strategy) => strategy.id === strategyId) || null;
}

export async function listDefiStrategyEvidence(): Promise<Record<string, DefiStrategyEvidence>> {
  const db = getDb();
  const participantRows = await db.prepare(
    `SELECT p.strategy_id, COUNT(DISTINCT LOWER(p.user_address)) AS participant_count, MAX(p.updated_at) AS updated_at
     FROM defi_positions p
     WHERE CAST(p.current_value_raw AS NUMERIC) > 0
       AND p.verification_source = 'chain_indexer'
       AND p.canonical = TRUE
     GROUP BY p.strategy_id`
  ).all() as Array<{ strategy_id: string; participant_count: number | string; updated_at: number | string }>;
  const yieldRows = await db.prepare(
    `SELECT strategy_id, COALESCE(SUM(CAST(amount_raw AS NUMERIC)), 0) AS yield_paid_raw, MAX(updated_at) AS updated_at
     FROM defi_transactions
     WHERE evidence_type = 'realized_service_fee'
       AND verification_source = 'chain_indexer'
       AND canonical = TRUE
       AND LOWER(status) IN ('complete', 'completed', 'confirmed', 'success')
       AND COALESCE(destination_tx_hash, source_tx_hash) IS NOT NULL
     GROUP BY strategy_id`
  ).all() as Array<{ strategy_id: string; yield_paid_raw: string | number; updated_at: number | string }>;
  const avatarRows = await db.prepare(
    `SELECT p.strategy_id, LOWER(p.user_address) AS user_address, MAX(p.updated_at) AS updated_at
     FROM defi_positions p
     LEFT JOIN user_settings s ON LOWER(s.address) = LOWER(p.user_address)
     WHERE CAST(p.current_value_raw AS NUMERIC) > 0
       AND p.verification_source = 'chain_indexer'
       AND p.canonical = TRUE
       AND COALESCE(s.privacy_hide_growth_activity, FALSE) = FALSE
     GROUP BY p.strategy_id, LOWER(p.user_address)
     ORDER BY updated_at DESC`
  ).all() as Array<{ strategy_id: string; user_address: string; updated_at: number | string }>;

  const yieldByStrategy = new Map(yieldRows.map((row) => [row.strategy_id, row]));
  const avatarAddresses = Array.from(new Set(avatarRows.map((row) => row.user_address))).slice(0, 100);
  const identities = await resolveAddressIdentities(avatarAddresses);
  const result: Record<string, DefiStrategyEvidence> = {};

  for (const participantRow of participantRows) {
    const yieldRow = yieldByStrategy.get(participantRow.strategy_id);
    const participantCount = Number(participantRow.participant_count || 0);
    const yieldPaidRaw = String(yieldRow?.yield_paid_raw || "0").split(".")[0] || "0";
    if (participantCount <= 0 || BigInt(yieldPaidRaw) <= 0n) continue;
    const participants = avatarRows
      .filter((row) => row.strategy_id === participantRow.strategy_id)
      .slice(0, 3)
      .map((row) => identities.get(row.user_address))
      .filter((identity): identity is NonNullable<typeof identity> => Boolean(identity))
      .map((identity) => ({
        displayName: identity.displayName,
        profileImageUrl: identity.profileImageUrl,
      }));
    result[participantRow.strategy_id] = {
      participantCount,
      yieldPaidRaw,
      updatedAt: Math.max(Number(participantRow.updated_at || 0), Number(yieldRow?.updated_at || 0)),
      participants,
    };
  }

  return result;
}

export function getDefiSummary() {
  const strategies = listDefiStrategies();
  const readyStrategyCount = strategies.filter((strategy) => strategy.status === "ready").length;
  const transactionEnabled = ENABLE_DEFI_TRANSACTIONS && strategies.some((strategy) => strategy.transactionEnabled);
  const configuredCommunityTotalRaw = process.env.DEFI_COMMUNITY_TOTAL_RAW?.trim();
  const configuredParticipantCount = Number(process.env.DEFI_PARTICIPANT_COUNT || 0);
  const strategyParticipantCount = strategies.reduce((sum, strategy) => sum + Number(strategy.participantCount || 0), 0);
  const communityTotalRaw = configuredCommunityTotalRaw || undefined;
  const participantCount = configuredParticipantCount > 0
    ? configuredParticipantCount
    : strategyParticipantCount > 0
      ? strategyParticipantCount
      : undefined;
  return {
    mode: transactionEnabled ? "transactions_enabled" : "preview_only",
    transactionEnabled,
    strategyCount: strategies.length,
    readyStrategyCount,
    providerCount: new Set(strategies.map((strategy) => strategy.provider)).size,
    communityTotalRaw,
    participantCount,
    guardrails: [
      "No beta transaction route is enabled unless ENABLE_DEFI_TRANSACTIONS=true.",
      "Wallet actions remain unavailable unless DEFI_TRANSACTION_ROUTE_READY=true.",
      "Strategies are configured by provider metadata, not hardcoded into frontend flows.",
      "Provider deployment addresses must be verified before a strategy can move to ready.",
    ],
  };
}

export async function listPreviewPositions(address: string): Promise<DefiPreviewPosition[]> {
  const db = getDb();
  const rows = await db
    .prepare(
      `SELECT id, strategy_id, principal_raw, current_value_raw, yield_earned_raw, shares_raw,
              target_address, verification_source, chain_state, updated_at
       FROM defi_positions
       WHERE lower(user_address) = lower(?)
         AND canonical = TRUE
       ORDER BY updated_at DESC`
    )
    .all(address) as Array<{
      id: string;
      strategy_id: string;
      principal_raw: string;
      current_value_raw: string;
      yield_earned_raw: string;
      shares_raw: string | null;
      target_address: string | null;
      verification_source: string | null;
      chain_state: string;
      updated_at: number;
    }>;

  if (rows.length > 0) {
    const client = createBackendPublicClient({ timeoutMs: Number(process.env.DISPLAY_RPC_TIMEOUT_MS || 4_000) });
    return Promise.all(rows.map(async (row) => {
      let currentValueRaw = row.current_value_raw;
      let updatedAt = row.updated_at;
      if (
        row.verification_source === "chain_indexer" &&
        row.target_address && isAddress(row.target_address) &&
        BigInt(row.shares_raw || "0") > 0n
      ) {
        try {
          const value = await client.readContract({
            address: getAddress(row.target_address) as `0x${string}`,
            abi: STRATEGY_PREVIEW_ABI,
            functionName: "previewRedeem",
            args: [BigInt(row.shares_raw || "0")],
          });
          currentValueRaw = value.toString();
          updatedAt = Date.now();
        } catch {
          // Indexed state remains the display fallback when fresh RPC reads fail.
        }
      }
      return {
        id: row.id,
        strategyId: row.strategy_id,
        status: "indexed" as const,
        principalRaw: row.principal_raw,
        currentValueRaw,
        yieldEarnedRaw: row.yield_earned_raw,
        chainState: row.chain_state,
        updatedAt,
      };
    }));
  }

  return [];
}

export async function listDefiActivity(address: string): Promise<DefiActivityRecord[]> {
  const db = getDb();
  const strategies = new Map(listDefiStrategies().map((strategy) => [strategy.id, strategy]));
  const rows = await db
    .prepare(
      `SELECT id, strategy_id, action, status, source_tx_hash, destination_tx_hash, amount_raw, error, metadata_json, created_at
       FROM defi_transactions
       WHERE lower(user_address) = lower(?)
         AND canonical = TRUE
       ORDER BY created_at DESC
       LIMIT 100`
    )
    .all(address) as Array<{
      id: string;
      strategy_id: string;
      action: string;
      status: string;
      source_tx_hash: string | null;
      destination_tx_hash: string | null;
      amount_raw: string | null;
      error: string | null;
      metadata_json: string | null;
      created_at: number;
    }>;

  if (rows.length > 0) {
    return rows.map((row) => {
      const strategy = strategies.get(row.strategy_id);
      const action = normalizeActivityAction(row.action);
      return {
        id: row.id,
        timestamp: row.created_at,
        action,
        strategyId: row.strategy_id,
        strategyName: strategy?.name || row.strategy_id,
        amountRaw: row.amount_raw || "0",
        direction: action === "withdraw" ? "out" : action === "details" || action === "watch" ? "neutral" : "in",
        status: normalizeActivityStatus(row.status),
        txHash: row.destination_tx_hash || row.source_tx_hash || undefined,
        detail: row.error || undefined,
      };
    });
  }

  return [];
}

function normalizeActivityAction(action: string): DefiActivityRecord["action"] {
  const normalized = action.toLowerCase();
  if (["deposit", "grow", "supply"].includes(normalized)) return "grow";
  if (["yield", "harvest", "interest"].includes(normalized)) return "yield";
  if (["withdraw", "exit", "redeem"].includes(normalized)) return "withdraw";
  if (["details", "view_details"].includes(normalized)) return "details";
  if (["watch", "watch_strategy"].includes(normalized)) return "watch";
  return "grow";
}

function normalizeActivityStatus(status: string): DefiActivityRecord["status"] {
  const normalized = status.toLowerCase();
  if (["pending", "processing"].includes(normalized)) return "pending";
  if (["complete", "completed", "confirmed", "success"].includes(normalized)) return "complete";
  if (["failed", "error"].includes(normalized)) return "failed";
  return "preview";
}
